import React from 'react';
import { 
  Zap, 
  ArrowRight, 
  TrendingUp, 
  Video,
  AlertCircle,
  CheckCircle2,
  Music,
  Users,
  Sparkles
} from 'lucide-react';
import { cn } from '../lib/utils';
import { DailyTask } from '../engine/growth';

export function DailyGamePlan({ tasks = [], onAction, isAI }: { tasks?: DailyTask[], onAction?: (msg: string) => void, isAI?: boolean }) {
  return (
    <section className="glass-card p-8">
      <div className="flex items-center justify-between mb-8">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-blue-600 rounded-lg shadow-lg shadow-blue-200">
            <Zap className="w-5 h-5 text-white fill-current" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-xl font-bold text-slate-900">Daily Game Plan</h3>
              {isAI && (
                <span className="flex items-center gap-1 px-2 py-0.5 bg-indigo-100 text-indigo-600 text-[9px] font-bold rounded-full uppercase tracking-widest">
                  <Sparkles className="w-2.5 h-2.5" />
                  AI Powered
                </span>
              )}
            </div>
            <p className="text-xs text-slate-500 font-medium">
              {isAI ? "Strategic actions generated by your AI Manager" : "Heuristic actions based on your current signals"}
            </p>
          </div>
        </div>
        {tasks.length > 0 && (
          <span className="text-[10px] font-bold text-blue-600 bg-blue-50 px-2 py-1 rounded-full uppercase tracking-widest">
            Updated 5m ago
          </span>
        )}
      </div>

      <div className="space-y-4">
        {tasks.length > 0 ? (
          tasks.map((task, i) => (
            <div 
              key={i} 
              className={cn(
                "p-5 rounded-2xl border transition-all hover:shadow-md group flex flex-col md:flex-row md:items-center justify-between gap-4",
                task.priority === 'high' && "bg-blue-50/30 border-blue-100 hover:border-blue-200",
                task.priority === 'medium' && "bg-emerald-50/30 border-emerald-100 hover:border-emerald-200",
                task.priority === 'low' && "bg-slate-50/30 border-slate-100 hover:border-slate-200"
              )}
            >
              <div className="flex gap-4">
                <div className={cn(
                  "w-10 h-10 rounded-xl flex items-center justify-center shrink-0",
                  task.category === 'Content' && "bg-blue-100 text-blue-600",
                  task.category === 'Release' && "bg-purple-100 text-purple-600",
                  task.category === 'Engagement' && "bg-emerald-100 text-emerald-600",
                  task.category === 'Admin' && "bg-slate-100 text-slate-600"
                )}>
                  {task.category === 'Content' && <Video className="w-5 h-5" />}
                  {task.category === 'Release' && <Music className="w-5 h-5" />}
                  {task.category === 'Engagement' && <Users className="w-5 h-5" />}
                  {task.category === 'Admin' && <AlertCircle className="w-5 h-5" />}
                </div>
                <div>
                  <h4 className="font-bold text-slate-900">{task.task}</h4>
                  <p className="text-sm text-slate-600 mt-1 leading-relaxed">{task.reason}</p>
                </div>
              </div>
              <button 
                onClick={() => onAction?.(`Started: ${task.task}`)}
                className={cn(
                  "btn-primary whitespace-nowrap px-6 py-2.5 text-sm",
                  task.priority === 'medium' && "bg-emerald-600 hover:bg-emerald-500",
                  task.priority === 'low' && "bg-slate-600 hover:bg-slate-500"
                )}
              >
                Take Action
                <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </button>
            </div>
          ))
        ) : (
          <div className="py-12 flex flex-col items-center justify-center text-center bg-slate-50/50 rounded-3xl border border-dashed border-slate-200">
            <div className="w-16 h-16 bg-white rounded-2xl flex items-center justify-center shadow-sm mb-4">
              <CheckCircle2 className="w-8 h-8 text-emerald-500" />
            </div>
            <h4 className="text-lg font-bold text-slate-900">All Caught Up!</h4>
            <p className="text-sm text-slate-500 max-w-[280px] mt-2">
              No urgent actions detected. Your artist ecosystem is running smoothly.
            </p>
          </div>
        )}
      </div>
    </section>
  );
}
